version: '3'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./biofuturo:/opt/biofuturo
      - ./test:/opt/test
      - ./letsencrypt/certs:/etc/letsencrypt/
    links:
      - mapa-biofuturo
      - test-passport
    ports:
      - "443:443"
  mapa-biofuturo:
    build:
        context: .
        dockerfile: web.dockerfile
    image: web:latest
    volumes:
      - ./biofuturo:/opt/biofuturo
    links:
      - db-biofuturo
  test-passport:
    build:
        context: .
        dockerfile: web.dockerfile
    image: web:latest
    volumes:
      - ./test:/opt/test
    links:
      - db-passport
  db-biofuturo:
    image: "mysql:5.7"
    volumes:
      - ./db-biofuturo:/var/lib/mysql
      - ./biofuturo/application/_installation:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
  db-passport:
    image: "mysql:5.7"
    volumes:
      - ./db-passport:/var/lib/mysql
      - ./test/application/_installation:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
